export default [
    {
        attack: 40,
        attackRange: 1,
        defence: 10,
        health: 50,
        level: 1,
        moveRange: 4,
        position: 0,
        turn: 'player',
        type: 'swordsman',
    },
    // {
    //     attack: 10,
    //     attackRange: 4,
    //     defence: 40,
    //     health: 50,
    //     level: 2,
    //     moveRange: 1,
    //     position: 11,
    //     turn: 'player',
    //     type: 'magician',
    // },
    // {
    //     attack: 40,
    //     attackRange: 1,
    //     defence: 10,
    //     health: 50,
    //     level: 2,
    //     moveRange: 4,
    //     position: 17,
    //     turn: 'player',
    //     type: 'swordsman',
    // },
    {
        attack: 25,
        attackRange: 2,
        defence: 25,
        health: 50,
        level: 2,
        moveRange: 2,
        position: 3,
        turn: 'AI',
        type: 'vampire',
    },
    // {
    //     attack: 10,
    //     attackRange: 2,
    //     defence: 40,
    //     health: 50,
    //     level: 2,
    //     moveRange: 2,
    //     position: 13,
    //     turn: 'AI',
    //     type: 'vampire',
    // }
]